# Generated by Django 5.0.6 on 2024-06-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
