# Generated by Django 5.0.6 on 2024-06-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyapp', '0003_remove_userdetails_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
