# Generated by Django 5.0.6 on 2024-06-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savvyapp', '0005_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
